### PR TITLE
diverse

### PR DESCRIPTION
**Pull request by peter1000**

### CODE REVIEW

**Comment by tnut** [comment]
I just think about update_pkgver will not work and is not necessary as Cards check the build date of the binary. Moreover the ports files are always copied from the port Directory (for ex /root/extra/cli-extra/os-prober ) to the Depot Directory and then compile in this Depot Directory

**Comment by peter1000** [comment]
`update_pkgver` does work quite well: Maybe I did not explain well what it does: 

Example: a Pkgfile which uses `cards` git source.

If I run `pkgmk` it will checkout the latest commit.

**Instead of having to update the Pkgfile version manually:** `update_pkgver` automatically.

I will later do a `cards git` Pkgfile for my collection.

**Comment by peter1000** [comment]
I think it was not too bad till now: mainly simple stuff - still have to do the `libpng issue`

**Comment by peter1000** [comment]
Finished - **Sorry for some overlooked issues: was quite a lot of moving around - and more than what I planned in the beginning*


Anyway, I hope the issues you pasted are fixed now: **This fixes could be merged.**

**I hope you like my general additions**

*  the added color output 
*  the added option to translate all using gettext 
*  and the additions of `git, svn, hg, bzr sources`.

If too much changed you could always go back to the version before I started and continue from there. In that case I would keep just a own fork of the: `pkgmk.in`

**Comment by tnut** [comment]
I want to thanks you for what you did. It's the first time somebody bring so much in so short time. I will now continue to make test on the new pkgmk script. 
Maybe to makes our futures easier, as I expect some others bugs  / missing stufs (working PO files for example), what do you think if we rename the pkgmk script file to anything you like and put back the original pkgmk script file created before all your commits. We could then make a smooth Transition without stress  whithout pressure. I could easily add a configurable pkgtool command line in Cards.conf file to be able to choose the one we should run

**Comment by peter1000** [comment]
Good Idea :+1: 

There are 2 ways to go about it.

1.

Not to release a new card version until  the new things tested and working

2. 
To rename the file as you suggested: for myself there is no need to add a special switch to card: 
I just overwrite the /usr/bin/pkgmk  with the file.

So whatever you wish is fine: probably to not break any old ports shipping the previous version would be best and rename the `pkgmk.in` to anything: e.g. `pkgmk_new.in`

I will do some more work on it: but be busy a couple of days  .. just to let you know ...

**Pull request merged**
