### PR TITLE
Adds support for additional: pkgdeps=() Pkgfile variable

### PR DESCRIPTION
**Pull request by peter1000**
EXAMPLE: Current Depends Comment line

```bash
# Depends on:   git wget subversion attr acl
```

EXAMPLE: bash one-line depends=() array inclusive "" ''

```bash
depends=(git wget "subversion" 'attr' acl bash)
```

EXAMPLE: bash multiline-line depends=() array inclusive comments

```bash
depends=(git # inline comment

	wget "subversion" 'attr'
acl  # Inline comment

	tar
)
```

Do we need to change the code somewhere else too?

I tried it with `cards deptree '

### CODE REVIEW

**Comment by tnut** [comment]
I'm glad you are also able to adjust some C++ code. I will take a close look at it. Be aware cards need to still work with existing syntax. After a quick look at your code, it seems to still do it

**Comment by tnut** [comment]
I think you want to have some more compat with archlinux with this PR in which case the variable should be named: makedepends. The var 'depend' Is in 95 % not need with cards (runtime deps)

**Comment by peter1000** [comment]
Actually I do not bother much about Arch: just want to get rid of the Comment line variables.

Anyway I'm writing a compatible function for alternative names.

Today I decided that for the bash library I will use internally only names which start with `pkg`.

| Variable Name | Compatibility Supported Names                                                                 |
|:--------------|:----------------------------------------------------------------------------------------------|
| `pkgpackager` | `packager`, `maintainer`     NOTE: if 'packager' is missing 'maintainer' will be used instead |
| `pkgdesc`     | `description`                                                                                 |
| `pkgurl`      | `url`                                                                                         |
| `pkgdeps`     | `depends`                                                                                     |
| `pkgname`     | `name`                                                                                        |
| `pkgvers`     | `version`, `pkgver`                                                                           |
| `pkgrel`      | `release`                                                                                     |
| `pkgsources`  | `source`                                                                                      |
| `pkgmd5sums`  |                                                                                               |

This will make it very clear that the variable comes from a Pkgfile: I got a bit confused with the `group` variable usage in pkgmk.in

---

This means if you want to merge this pull-request I would have to rename  this `depends` to `pkgdeps` JUST LET ME KNOW

I hope that next week I can get the new basic bash version working.

**Comment by peter1000** [comment]
changed the pullrequest to final name: `pkgdeps=()`

**Comment by tnut** [comment]
This time, I totally disagreed. I don't see any prob to have "variable" hidden in a comment. As you see I anyway look for the string : #dep means folllowings examples are  all working:
"# dep:"
"# Dep:"
"# Depends:"
"# Depends on:"
"# depends:"
the <package_name.deps file can also work but this feature I should probably drop
it's so confortable
Also, for me the only reason to get read of (some of) thoses comment variables was to make indeed the recept of archlinux and CRUX as much as compatible with cards
I strongly recomend you to not create still other variables. Users will be losten

**Comment by peter1000** [comment]
> This time, I totally disagreed. 

No problem at all. 

if you still want to merge the support for a dependency array we can rename it to: "makedepends"

otherwise you can also just close the pull-request.

**Comment by tnut** [comment]
I'm checking where it's use and will merge and rename to makedepends. For me what is important here is backward compatibility

**Comment by peter1000** [comment]
> will merge and rename to makedepends

good idea :+1:

**Pull request merged**
